title: "Rohith Maben"
description: "Aeronautical Engineer • UAV Systems • Researcher"
theme: jekyll-theme-modernist
show_downloads: false

# Optional customization
author: Rohith Maben
social_links:
  linkedin: "https://www.linkedin.com/in/rohithmaben"
  github: "https://github.com/rohith8272"
  email: "rohith8272@gmail.com"


